name: Manual CI

on:
  push:
    paths:
      - "*.org"
      - "*.png"
      - "*.jpg"
      - ".github/workflows/Manual-CI.yaml"

jobs:
  build:
    strategy:
      matrix:
        file: [RULESET, RISK_AGENT_GUIDE]
    name: Build ${{ matrix.file }}
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Build Org
        uses: docker://pandoc/latex:2.19.2.0
        with:
          args: >-
            --resource-path manual
            --from org
            --to latex
            --output ${{ matrix.file }}.pdf
            manual/${{ matrix.file }}.org
