name: Prerelease

on:
  push:
    tags:
      - "v*.*.*-SNAPSHOT"
      - "v*.*.*-SNAPSHOT-*"

jobs:
  manual:
    strategy:
      matrix:
        file: [ RULESET, RISK_AGENT_GUIDE ]
    name: Build ${{ matrix.file }}
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Build Org
        uses: docker://pandoc/latex:2.14.0.1
        with:
          args: >-
            --from org
            --to latex
            --output ${{ matrix.file }}.pdf
            ${{ matrix.file }}.org
      - uses: actions/upload-artifact@v2
        with:
          name: manual
          path: ${{ matrix.file }}
  jars:
    name: Build jar, shadowJar, javadoc and sources
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: zulu
          cache: gradle
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Build with Gradle
        shell: bash
        run: ./gradlew --parallel jar shadowJar javadocJar sources
      - name: Upload Jar
        uses: actions/upload-artifact@v2
        with:
          name: jar
          path: |
            build/libs/sge-risk-*.*.*-SNAPSHOT.jar
            !build/libs/sge-risk-*.*.*-SNAPSHOT-*.jar
      - name: Upload sources
        uses: actions/upload-artifact@v2
        with:
          name: sources
          path: build/libs/sge-risk-*.*.*-SNAPSHOT-sources.jar
      - name: Upload javadoc
        uses: actions/upload-artifact@v2
        with:
          name: javadoc
          path: build/libs/sge-risk-*.*.*-SNAPSHOT-javadoc.jar
      - name: Upload shadow
        uses: actions/upload-artifact@v2
        with:
          name: shadow
          path: build/libs/sge-risk-*.*.*-SNAPSHOT-exe.jar

  github_packages:
    name: Release as github package
    needs: jars
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: zulu
          cache: gradle
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Ensure build/libs/ exists
        run: mkdir -p build/libs/
      - name: Download jar
        uses: actions/download-artifact@v2
        with:
          name: jar
          path: build/libs/
      - name: Download sources
        uses: actions/download-artifact@v2
        with:
          name: sources
          path: build/libs/
      - name: Download javadoc
        uses: actions/download-artifact@v2
        with:
          name: javadoc
          path: build/libs/
      - name: Publish package
        run: ./gradlew publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  github_release:
    name: Release on github
    runs-on: ubuntu-20.04
    needs:
      - jars
      - manual
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          files: |
            jar/sge-risk-*.*.*-SNAPSHOT.jar
            shadow/sge-risk-*.*.*-SNAPSHOT-exe.jar
            sources/sge-risk-*.*.*-SNAPSHOT-sources.jar
            javadoc/sge-risk-*.*.*-SNAPSHOT-javadoc.jar
            manual/RULESET.pdf
            manual/RISK_AGENT_GUIDE.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

